### ISSUE TITLE
Smoke tests of examples in CI

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious-academy#2]
## Problem

Examples of REST API may become broken after updating the demo due to API changes. We don't want to manually test all examples.
## Proposal

Run each example on a CI after an udpate of the demo.

@davidrapin @francescoinfante thoughts?

**Comment by davidrapin** [comment]
Proposal:
- replace direct API use by https://github.com/Linkurious/linkurious-rest-client/
- add tests for all APIs in Linkurious REST Client

**Comment by sheymann** [comment]
Closed because it will be fixed by #3
